spring:
  application:
    name: auth-service
server:
  port: ${SERVER_PORT:8094}
jwt:
  secret: ${JWT_SECRET:c9998dbc291932efc08976fbfa62e55567176134c70f34a200b0b6883f19f30c}
  token:
    validity: ${JWT_TOKEN_VALIDITY:18000000}
aws:
  access:
    key: ${AWS_ACCESS_KEY:key1}
    secretkey: ${AWS_ACCESS_SECRET_KEY:key2}
  region: ${AWS_REGION:us-east-2}
  dynamodb:
    endpoint:
      url: ${AWS_DYNAMODB_URL:http://localhost:8000/}
      
#eureka:
#   client:
#      serviceUrl:
#         defaultZone: http://${EUREKA_SERVER:localhost}:8761/eureka